/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.clicdirectory.tables.records.AlbumsRecord, java.lang.Long> IDENTITY_ALBUMS = Identities0.IDENTITY_ALBUMS;
	public static final org.jooq.Identity<com.clicdirectory.tables.records.ExpRecord, java.lang.Long> IDENTITY_EXP = Identities0.IDENTITY_EXP;
	public static final org.jooq.Identity<com.clicdirectory.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = Identities0.IDENTITY_MEMBER;
	public static final org.jooq.Identity<com.clicdirectory.tables.records.SongsRecord, java.lang.Long> IDENTITY_SONGS = Identities0.IDENTITY_SONGS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.AlbumsRecord> ALBUMS_LINK_KEY = UniqueKeys0.ALBUMS_LINK_KEY;
	public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.AlbumsRecord> ALBUMS_PKEY = UniqueKeys0.ALBUMS_PKEY;
	public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.MemberRecord> MEMBER_PKEY = UniqueKeys0.MEMBER_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.clicdirectory.tables.records.SongsRecord, com.clicdirectory.tables.records.AlbumsRecord> SONGS__SONGS_ALBUM_ID_FKEY = ForeignKeys0.SONGS__SONGS_ALBUM_ID_FKEY;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.clicdirectory.tables.records.AlbumsRecord, java.lang.Long> IDENTITY_ALBUMS = createIdentity(com.clicdirectory.tables.Albums.ALBUMS, com.clicdirectory.tables.Albums.ALBUMS.ID);
		public static org.jooq.Identity<com.clicdirectory.tables.records.ExpRecord, java.lang.Long> IDENTITY_EXP = createIdentity(com.clicdirectory.tables.Exp.EXP, com.clicdirectory.tables.Exp.EXP.ID);
		public static org.jooq.Identity<com.clicdirectory.tables.records.MemberRecord, java.lang.Long> IDENTITY_MEMBER = createIdentity(com.clicdirectory.tables.Member.MEMBER, com.clicdirectory.tables.Member.MEMBER.ID);
		public static org.jooq.Identity<com.clicdirectory.tables.records.SongsRecord, java.lang.Long> IDENTITY_SONGS = createIdentity(com.clicdirectory.tables.Songs.SONGS, com.clicdirectory.tables.Songs.SONGS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.AlbumsRecord> ALBUMS_LINK_KEY = createUniqueKey(com.clicdirectory.tables.Albums.ALBUMS, com.clicdirectory.tables.Albums.ALBUMS.LINK);
		public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.AlbumsRecord> ALBUMS_PKEY = createUniqueKey(com.clicdirectory.tables.Albums.ALBUMS, com.clicdirectory.tables.Albums.ALBUMS.ID);
		public static final org.jooq.UniqueKey<com.clicdirectory.tables.records.MemberRecord> MEMBER_PKEY = createUniqueKey(com.clicdirectory.tables.Member.MEMBER, com.clicdirectory.tables.Member.MEMBER.EMAIL);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.clicdirectory.tables.records.SongsRecord, com.clicdirectory.tables.records.AlbumsRecord> SONGS__SONGS_ALBUM_ID_FKEY = createForeignKey(com.clicdirectory.Keys.ALBUMS_PKEY, com.clicdirectory.tables.Songs.SONGS, com.clicdirectory.tables.Songs.SONGS.ALBUM_ID);
	}
}
