/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.emp
	 */
	public static final com.clicdirectory.tables.Emp EMP = com.clicdirectory.tables.Emp.EMP;

	/**
	 * The table public.emp2
	 */
	public static final com.clicdirectory.tables.Emp2 EMP2 = com.clicdirectory.tables.Emp2.EMP2;

	/**
	 * The table public.leaderboard
	 */
	public static final com.clicdirectory.tables.Leaderboard LEADERBOARD = com.clicdirectory.tables.Leaderboard.LEADERBOARD;

	/**
	 * The table public.link
	 */
	public static final com.clicdirectory.tables.Link LINK = com.clicdirectory.tables.Link.LINK;

	/**
	 * The table public.Member
	 */
	public static final com.clicdirectory.tables.Member MEMBER = com.clicdirectory.tables.Member.MEMBER;

	/**
	 * The table public.Test
	 */
	public static final com.clicdirectory.tables.Test TEST = com.clicdirectory.tables.Test.TEST;
}
