/**
 * This class is generated by jOOQ
 */
package com.clicdirectory;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.albums
	 */
	public static final com.clicdirectory.tables.Albums ALBUMS = com.clicdirectory.tables.Albums.ALBUMS;

	/**
	 * The table public.data
	 */
	public static final com.clicdirectory.tables.Data DATA = com.clicdirectory.tables.Data.DATA;

	/**
	 * The table public.exp
	 */
	public static final com.clicdirectory.tables.Exp EXP = com.clicdirectory.tables.Exp.EXP;

	/**
	 * The table public.member
	 */
	public static final com.clicdirectory.tables.Member MEMBER = com.clicdirectory.tables.Member.MEMBER;

	/**
	 * The table public.songs
	 */
	public static final com.clicdirectory.tables.Songs SONGS = com.clicdirectory.tables.Songs.SONGS;
}
