/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Data extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.DataRecord> {

	private static final long serialVersionUID = -331812088;

	/**
	 * The singleton instance of <code>public.data</code>
	 */
	public static final com.clicdirectory.tables.Data DATA = new com.clicdirectory.tables.Data();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.DataRecord> getRecordType() {
		return com.clicdirectory.tables.records.DataRecord.class;
	}

	/**
	 * The column <code>public.data.image</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.DataRecord, java.lang.String> IMAGE = createField("image", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.data.Album</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.DataRecord, java.lang.String> ALBUM = createField("Album", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>public.data</code> table reference
	 */
	public Data() {
		this("data", null);
	}

	/**
	 * Create an aliased <code>public.data</code> table reference
	 */
	public Data(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Data.DATA);
	}

	private Data(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.DataRecord> aliased) {
		this(alias, aliased, null);
	}

	private Data(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.DataRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Data as(java.lang.String alias) {
		return new com.clicdirectory.tables.Data(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Data rename(java.lang.String name) {
		return new com.clicdirectory.tables.Data(name, null);
	}
}
