/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emp extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.EmpRecord> {

	private static final long serialVersionUID = 1965273196;

	/**
	 * The singleton instance of <code>public.emp</code>
	 */
	public static final com.clicdirectory.tables.Emp EMP = new com.clicdirectory.tables.Emp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.EmpRecord> getRecordType() {
		return com.clicdirectory.tables.records.EmpRecord.class;
	}

	/**
	 * The column <code>public.emp.name</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp.email</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>public.emp.pass</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> PASS = createField("pass", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp.Age</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> AGE = createField("Age", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp.Address</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> ADDRESS = createField("Address", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp.phone</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.EmpRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * Create a <code>public.emp</code> table reference
	 */
	public Emp() {
		this("emp", null);
	}

	/**
	 * Create an aliased <code>public.emp</code> table reference
	 */
	public Emp(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Emp.EMP);
	}

	private Emp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.EmpRecord> aliased) {
		this(alias, aliased, null);
	}

	private Emp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.EmpRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Emp as(java.lang.String alias) {
		return new com.clicdirectory.tables.Emp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Emp rename(java.lang.String name) {
		return new com.clicdirectory.tables.Emp(name, null);
	}
}
