/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emp2 extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.Emp2Record> {

	private static final long serialVersionUID = 536153910;

	/**
	 * The singleton instance of <code>public.emp2</code>
	 */
	public static final com.clicdirectory.tables.Emp2 EMP2 = new com.clicdirectory.tables.Emp2();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.Emp2Record> getRecordType() {
		return com.clicdirectory.tables.records.Emp2Record.class;
	}

	/**
	 * The column <code>public.emp2.name</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp2.product_name</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> PRODUCT_NAME = createField("product_name", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>public.emp2.product_id</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp2.purchase_date</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> PURCHASE_DATE = createField("purchase_date", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp2.address</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.emp2.phone</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.Emp2Record, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * Create a <code>public.emp2</code> table reference
	 */
	public Emp2() {
		this("emp2", null);
	}

	/**
	 * Create an aliased <code>public.emp2</code> table reference
	 */
	public Emp2(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Emp2.EMP2);
	}

	private Emp2(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.Emp2Record> aliased) {
		this(alias, aliased, null);
	}

	private Emp2(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.Emp2Record> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Emp2 as(java.lang.String alias) {
		return new com.clicdirectory.tables.Emp2(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Emp2 rename(java.lang.String name) {
		return new com.clicdirectory.tables.Emp2(name, null);
	}
}
