/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exp extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.ExpRecord> {

	private static final long serialVersionUID = 1052387326;

	/**
	 * The singleton instance of <code>public.exp</code>
	 */
	public static final com.clicdirectory.tables.Exp EXP = new com.clicdirectory.tables.Exp();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.ExpRecord> getRecordType() {
		return com.clicdirectory.tables.records.ExpRecord.class;
	}

	/**
	 * The column <code>public.exp.movie</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> MOVIE = createField("movie", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.exp.link</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> LINK = createField("link", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.exp.img</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> IMG = createField("img", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.exp.is_fetched</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.Boolean> IS_FETCHED = createField("is_fetched", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.exp.released</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> RELEASED = createField("released", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.exp.cast</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> CAST = createField("cast", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

	/**
	 * The column <code>public.exp.director</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.String> DIRECTOR = createField("director", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.exp.id</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.ExpRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.exp</code> table reference
	 */
	public Exp() {
		this("exp", null);
	}

	/**
	 * Create an aliased <code>public.exp</code> table reference
	 */
	public Exp(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Exp.EXP);
	}

	private Exp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.ExpRecord> aliased) {
		this(alias, aliased, null);
	}

	private Exp(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.ExpRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.clicdirectory.tables.records.ExpRecord, java.lang.Long> getIdentity() {
		return com.clicdirectory.Keys.IDENTITY_EXP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Exp as(java.lang.String alias) {
		return new com.clicdirectory.tables.Exp(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Exp rename(java.lang.String name) {
		return new com.clicdirectory.tables.Exp(name, null);
	}
}
