/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Leaderboard extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.LeaderboardRecord> {

	private static final long serialVersionUID = -80635699;

	/**
	 * The singleton instance of <code>public.leaderboard</code>
	 */
	public static final com.clicdirectory.tables.Leaderboard LEADERBOARD = new com.clicdirectory.tables.Leaderboard();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.LeaderboardRecord> getRecordType() {
		return com.clicdirectory.tables.records.LeaderboardRecord.class;
	}

	/**
	 * The column <code>public.leaderboard.id</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.leaderboard.phone</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.leaderboard.token</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.leaderboard.password</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.leaderboard.email</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.leaderboard.role</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.leaderboard.fb_token</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.String> FB_TOKEN = createField("fb_token", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.leaderboard.points</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.Integer> POINTS = createField("points", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.leaderboard.postsshared</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.Integer> POSTSSHARED = createField("postsshared", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.leaderboard.level</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LeaderboardRecord, java.lang.Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.leaderboard</code> table reference
	 */
	public Leaderboard() {
		this("leaderboard", null);
	}

	/**
	 * Create an aliased <code>public.leaderboard</code> table reference
	 */
	public Leaderboard(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Leaderboard.LEADERBOARD);
	}

	private Leaderboard(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.LeaderboardRecord> aliased) {
		this(alias, aliased, null);
	}

	private Leaderboard(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.LeaderboardRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Leaderboard as(java.lang.String alias) {
		return new com.clicdirectory.tables.Leaderboard(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Leaderboard rename(java.lang.String name) {
		return new com.clicdirectory.tables.Leaderboard(name, null);
	}
}
