/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Link extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.LinkRecord> {

	private static final long serialVersionUID = -612799770;

	/**
	 * The singleton instance of <code>public.link</code>
	 */
	public static final com.clicdirectory.tables.Link LINK = new com.clicdirectory.tables.Link();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.LinkRecord> getRecordType() {
		return com.clicdirectory.tables.records.LinkRecord.class;
	}

	/**
	 * The column <code>public.link.post</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.LinkRecord, java.lang.String> POST = createField("post", org.jooq.impl.SQLDataType.VARCHAR.length(2000), this, "");

	/**
	 * Create a <code>public.link</code> table reference
	 */
	public Link() {
		this("link", null);
	}

	/**
	 * Create an aliased <code>public.link</code> table reference
	 */
	public Link(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Link.LINK);
	}

	private Link(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.LinkRecord> aliased) {
		this(alias, aliased, null);
	}

	private Link(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.LinkRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Link as(java.lang.String alias) {
		return new com.clicdirectory.tables.Link(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Link rename(java.lang.String name) {
		return new com.clicdirectory.tables.Link(name, null);
	}
}
