/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Member extends org.jooq.impl.TableImpl<com.clicdirectory.tables.records.MemberRecord> {

	private static final long serialVersionUID = 1415340491;

	/**
	 * The singleton instance of <code>public.Member</code>
	 */
	public static final com.clicdirectory.tables.Member MEMBER = new com.clicdirectory.tables.Member();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.clicdirectory.tables.records.MemberRecord> getRecordType() {
		return com.clicdirectory.tables.records.MemberRecord.class;
	}

	/**
	 * The column <code>public.Member.id</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.Member.phone</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Member.token</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.Member.password</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.Member.email</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.Member.role</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.Member.fb_token</code>.
	 */
	public final org.jooq.TableField<com.clicdirectory.tables.records.MemberRecord, java.lang.String> FB_TOKEN = createField("fb_token", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * Create a <code>public.Member</code> table reference
	 */
	public Member() {
		this("Member", null);
	}

	/**
	 * Create an aliased <code>public.Member</code> table reference
	 */
	public Member(java.lang.String alias) {
		this(alias, com.clicdirectory.tables.Member.MEMBER);
	}

	private Member(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.MemberRecord> aliased) {
		this(alias, aliased, null);
	}

	private Member(java.lang.String alias, org.jooq.Table<com.clicdirectory.tables.records.MemberRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.clicdirectory.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.clicdirectory.tables.Member as(java.lang.String alias) {
		return new com.clicdirectory.tables.Member(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.clicdirectory.tables.Member rename(java.lang.String name) {
		return new com.clicdirectory.tables.Member(name, null);
	}
}
