/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emp2Record extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.Emp2Record> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1842348345;

	/**
	 * Setter for <code>public.emp2.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.emp2.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.emp2.product_name</code>.
	 */
	public void setProductName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.emp2.product_name</code>.
	 */
	public java.lang.String getProductName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.emp2.product_id</code>.
	 */
	public void setProductId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.emp2.product_id</code>.
	 */
	public java.lang.String getProductId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.emp2.purchase_date</code>.
	 */
	public void setPurchaseDate(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.emp2.purchase_date</code>.
	 */
	public java.lang.String getPurchaseDate() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.emp2.address</code>.
	 */
	public void setAddress(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.emp2.address</code>.
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.emp2.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.emp2.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Emp2.EMP2.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.clicdirectory.tables.Emp2.EMP2.PRODUCT_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.clicdirectory.tables.Emp2.EMP2.PRODUCT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.clicdirectory.tables.Emp2.EMP2.PURCHASE_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.clicdirectory.tables.Emp2.EMP2.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.clicdirectory.tables.Emp2.EMP2.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getProductName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getProductId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPurchaseDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value2(java.lang.String value) {
		setProductName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value3(java.lang.String value) {
		setProductId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value4(java.lang.String value) {
		setPurchaseDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value5(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record value6(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Emp2Record values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached Emp2Record
	 */
	public Emp2Record() {
		super(com.clicdirectory.tables.Emp2.EMP2);
	}

	/**
	 * Create a detached, initialised Emp2Record
	 */
	public Emp2Record(java.lang.String name, java.lang.String productName, java.lang.String productId, java.lang.String purchaseDate, java.lang.String address, java.lang.String phone) {
		super(com.clicdirectory.tables.Emp2.EMP2);

		setValue(0, name);
		setValue(1, productName);
		setValue(2, productId);
		setValue(3, purchaseDate);
		setValue(4, address);
		setValue(5, phone);
	}
}
