/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LeaderboardRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.LeaderboardRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -128071049;

	/**
	 * Setter for <code>public.leaderboard.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.leaderboard.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.leaderboard.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.leaderboard.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.leaderboard.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.leaderboard.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.leaderboard.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.leaderboard.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.leaderboard.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.leaderboard.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.leaderboard.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.leaderboard.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.leaderboard.fb_token</code>.
	 */
	public void setFbToken(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.leaderboard.fb_token</code>.
	 */
	public java.lang.String getFbToken() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.leaderboard.points</code>.
	 */
	public void setPoints(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.leaderboard.points</code>.
	 */
	public java.lang.Integer getPoints() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.leaderboard.postsshared</code>.
	 */
	public void setPostsshared(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.leaderboard.postsshared</code>.
	 */
	public java.lang.Integer getPostsshared() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>public.leaderboard.level</code>.
	 */
	public void setLevel(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.leaderboard.level</code>.
	 */
	public java.lang.Integer getLevel() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.FB_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.POINTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.POSTSSHARED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.clicdirectory.tables.Leaderboard.LEADERBOARD.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getFbToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getPoints();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getPostsshared();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value2(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value3(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value4(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value5(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value6(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value7(java.lang.String value) {
		setFbToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value8(java.lang.Integer value) {
		setPoints(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value9(java.lang.Integer value) {
		setPostsshared(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord value10(java.lang.Integer value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LeaderboardRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LeaderboardRecord
	 */
	public LeaderboardRecord() {
		super(com.clicdirectory.tables.Leaderboard.LEADERBOARD);
	}

	/**
	 * Create a detached, initialised LeaderboardRecord
	 */
	public LeaderboardRecord(java.lang.Integer id, java.lang.String phone, java.lang.String token, java.lang.String password, java.lang.String email, java.lang.String role, java.lang.String fbToken, java.lang.Integer points, java.lang.Integer postsshared, java.lang.Integer level) {
		super(com.clicdirectory.tables.Leaderboard.LEADERBOARD);

		setValue(0, id);
		setValue(1, phone);
		setValue(2, token);
		setValue(3, password);
		setValue(4, email);
		setValue(5, role);
		setValue(6, fbToken);
		setValue(7, points);
		setValue(8, postsshared);
		setValue(9, level);
	}
}
