/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LinkRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.LinkRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = -552102972;

	/**
	 * Setter for <code>public.link.post</code>.
	 */
	public void setPost(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.link.post</code>.
	 */
	public java.lang.String getPost() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.clicdirectory.tables.Link.LINK.POST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getPost();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord value1(java.lang.String value) {
		setPost(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LinkRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LinkRecord
	 */
	public LinkRecord() {
		super(com.clicdirectory.tables.Link.LINK);
	}

	/**
	 * Create a detached, initialised LinkRecord
	 */
	public LinkRecord(java.lang.String post) {
		super(com.clicdirectory.tables.Link.LINK);

		setValue(0, post);
	}
}
