/**
 * This class is generated by jOOQ
 */
package com.clicdirectory.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MemberRecord extends org.jooq.impl.TableRecordImpl<com.clicdirectory.tables.records.MemberRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1032421477;

	/**
	 * Setter for <code>public.Member.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Member.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.Member.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Member.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.Member.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Member.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.Member.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Member.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.Member.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Member.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.Member.role</code>.
	 */
	public void setRole(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.Member.role</code>.
	 */
	public java.lang.String getRole() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.Member.fb_token</code>.
	 */
	public void setFbToken(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.Member.fb_token</code>.
	 */
	public java.lang.String getFbToken() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.clicdirectory.tables.Member.MEMBER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.clicdirectory.tables.Member.MEMBER.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.clicdirectory.tables.Member.MEMBER.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.clicdirectory.tables.Member.MEMBER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.clicdirectory.tables.Member.MEMBER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.clicdirectory.tables.Member.MEMBER.ROLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.clicdirectory.tables.Member.MEMBER.FB_TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getRole();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getFbToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value2(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value3(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value4(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value5(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value6(java.lang.String value) {
		setRole(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord value7(java.lang.String value) {
		setFbToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MemberRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MemberRecord
	 */
	public MemberRecord() {
		super(com.clicdirectory.tables.Member.MEMBER);
	}

	/**
	 * Create a detached, initialised MemberRecord
	 */
	public MemberRecord(java.lang.Integer id, java.lang.String phone, java.lang.String token, java.lang.String password, java.lang.String email, java.lang.String role, java.lang.String fbToken) {
		super(com.clicdirectory.tables.Member.MEMBER);

		setValue(0, id);
		setValue(1, phone);
		setValue(2, token);
		setValue(3, password);
		setValue(4, email);
		setValue(5, role);
		setValue(6, fbToken);
	}
}
